export interface Topic {
  id: string
  text: string
  isHeader?: boolean
  subject?: string // Added subject field for clarity
}

export interface DayData {
  day: number
  title: string
  subtitle: string
  subject: string // Added subject field
  topics: Topic[]
}

export const studyData: DayData[] = [
  {
    day: 1,
    title: "OS Warm-Up (Short Day)",
    subtitle: "UNIT II – Processes & Scheduling (Intro Only Today)",
    subject: "Operating Systems", // Added subject
    topics: [
      { id: "d1-h1", text: "1. Process Concepts", isHeader: true },
      { id: "d1-1", text: "What is a Process" },
      { id: "d1-2", text: "Program vs Process" },
      { id: "d1-3", text: "PCB (Process Control Block)" },
      { id: "d1-4", text: "Components: code, data, stack" },
      { id: "d1-5", text: "Process States (with diagram)" },
      { id: "d1-6", text: "State transitions explanation" },
      { id: "d1-h2", text: "2. CPU Scheduling (Basics)", isHeader: true },
      { id: "d1-7", text: "Need for Scheduling" },
      { id: "d1-8", text: "Non-preemptive scheduling" },
      { id: "d1-9", text: "FCFS basics" },
      { id: "d1-10", text: "SJF basics" },
      { id: "d1-11", text: "Simple Gantt chart examples" },
      { id: "d1-h3", text: "ML Intro (15 mins)", isHeader: true },
      { id: "d1-12", text: "Supervised Learning: meaning + 2 examples" },
      { id: "d1-13", text: "Unsupervised Learning: meaning + 2 examples" },
    ],
  },
  {
    day: 2,
    title: "OS UNIT II (FULL)",
    subtitle: "UNIT II – Processes, CPU Scheduling & Synchronization",
    subject: "Operating Systems",
    topics: [
      { id: "d2-h1", text: "1. Full CPU Scheduling Algorithms", isHeader: true },
      { id: "d2-1", text: "FCFS (solve 1 numerical)" },
      { id: "d2-2", text: "SJF: preemptive & non-preemptive" },
      { id: "d2-3", text: "Priority scheduling" },
      { id: "d2-4", text: "Round Robin (time quantum logic)" },
      { id: "d2-5", text: "Scheduling criteria: CPU utilization, throughput, TAT, WT, RT" },
      { id: "d2-h2", text: "2. Process Synchronization", isHeader: true },
      { id: "d2-6", text: "Critical Section Problem" },
      { id: "d2-7", text: "Requirements: Mutual Exclusion, Progress, Bounded Waiting" },
      { id: "d2-8", text: "Peterson's Solution (pseudo-code + explanation)" },
      { id: "d2-9", text: "Semaphores (binary vs counting)" },
      { id: "d2-10", text: "wait() and signal()" },
      { id: "d2-11", text: "Producer–consumer example" },
      { id: "d2-h3", text: "3. Revision", isHeader: true },
      { id: "d2-12", text: "Review Day 1 notes" },
    ],
  },
  {
    day: 3,
    title: "OS UNIT III (Memory + Deadlocks)",
    subtitle: "UNIT III – Memory Management & Deadlocks",
    subject: "Operating Systems",
    topics: [
      { id: "d3-h1", text: "1. Memory Management Basics", isHeader: true },
      { id: "d3-1", text: "Logical vs Physical Address" },
      { id: "d3-2", text: "Swapping" },
      { id: "d3-3", text: "Contiguous Allocation" },
      { id: "d3-4", text: "Fragmentation" },
      { id: "d3-h2", text: "2. Paging", isHeader: true },
      { id: "d3-5", text: "Page table" },
      { id: "d3-6", text: "Frame/Offset" },
      { id: "d3-7", text: "Address translation example" },
      { id: "d3-8", text: "TLB (concept)" },
      { id: "d3-h3", text: "3. Segmentation", isHeader: true },
      { id: "d3-9", text: "Segment table" },
      { id: "d3-10", text: "Segment addressing" },
      { id: "d3-h4", text: "4. Virtual Memory", isHeader: true },
      { id: "d3-11", text: "Demand paging" },
      { id: "d3-12", text: "Page fault" },
      { id: "d3-13", text: "Page replacement (FIFO, Optimal, LRU)" },
      { id: "d3-14", text: "Thrashing" },
      { id: "d3-h5", text: "5. Deadlocks", isHeader: true },
      { id: "d3-15", text: "System model" },
      { id: "d3-16", text: "Deadlock characterization" },
      { id: "d3-17", text: "Necessary conditions" },
      { id: "d3-18", text: "Prevention" },
      { id: "d3-19", text: "Avoidance (Banker's)" },
      { id: "d3-20", text: "Detection" },
      { id: "d3-21", text: "Recovery" },
      { id: "d3-22", text: "RAG example" },
    ],
  },
  {
    day: 4,
    title: "OS UNIT I & IV (Wrap-Up + PYQs)",
    subtitle: "UNIT I – Introduction to OS & UNIT IV – File & Security",
    subject: "Operating Systems",
    topics: [
      { id: "d4-h1", text: "UNIT I – Introduction to OS", isHeader: true },
      { id: "d4-1", text: "What is OS" },
      { id: "d4-2", text: "Functions" },
      { id: "d4-3", text: "Batch, Multiprogramming, Time-Sharing, Distributed, Real-Time systems" },
      { id: "d4-h2", text: "UNIT IV – File & Security", isHeader: true },
      { id: "d4-4", text: "File attributes" },
      { id: "d4-5", text: "File operations" },
      { id: "d4-6", text: "Access methods" },
      { id: "d4-7", text: "Directory structures: single, two-level, tree, acyclic, general graph" },
      { id: "d4-h3", text: "Linux File Security", isHeader: true },
      { id: "d4-8", text: "rwx" },
      { id: "d4-9", text: "chmod symbolic" },
      { id: "d4-10", text: "chmod numeric" },
      { id: "d4-11", text: "Permission examples" },
      { id: "d4-h4", text: "PYQs", isHeader: true },
      { id: "d4-12", text: "4 scheduling" },
      { id: "d4-13", text: "2 deadlock" },
      { id: "d4-14", text: "2 memory mgmt" },
    ],
  },
  {
    day: 5,
    title: "CG UNIT I (Basics + Algorithms)",
    subtitle: "Computer Graphics – Fundamentals & Line/Circle Algorithms",
    subject: "Computer Graphics",
    topics: [
      { id: "d5-1", text: "Raster vs Random scan" },
      { id: "d5-2", text: "Resolution, aspect ratio" },
      { id: "d5-3", text: "DDA" },
      { id: "d5-4", text: "Bresenham Line" },
      { id: "d5-5", text: "Bresenham Circle" },
      { id: "d5-6", text: "Aliasing & antialiasing" },
    ],
  },
  {
    day: 6,
    title: "CG UNIT II (Clipping + 2D Transforms)",
    subtitle: "Computer Graphics – Clipping & 2D Transformations",
    subject: "Computer Graphics",
    topics: [
      { id: "d6-1", text: "Cohen–Sutherland" },
      { id: "d6-2", text: "Cyrus–Beck" },
      { id: "d6-3", text: "2D transforms (translate, scale, rotate)" },
      { id: "d6-4", text: "Composite transforms" },
      { id: "d6-5", text: "Homogeneous coordinates" },
      { id: "d6-6", text: "Window–viewport mapping" },
    ],
  },
  {
    day: 7,
    title: "CG UNITS III & IV (Curves, Shading, 3D)",
    subtitle: "Computer Graphics – Curves, Shading & 3D Concepts",
    subject: "Computer Graphics",
    topics: [
      { id: "d7-1", text: "Hermite, Bezier, B-Spline" },
      { id: "d7-2", text: "Curve continuity (C0, C1, G1 – light)" },
      { id: "d7-3", text: "Shading: Gouraud, Phong" },
      { id: "d7-4", text: "Projections: ortho, axonometric, oblique, perspective" },
      { id: "d7-5", text: "Hidden surface removal: Z-buffer, Painter" },
    ],
  },
  {
    day: 8,
    title: "CC UNIT I & II",
    subtitle: "Cloud Computing – Overview & Architecture",
    subject: "Cloud Computing",
    topics: [
      { id: "d8-1", text: "Cloud Overview + Architecture" },
      { id: "d8-2", text: "Essential characteristics" },
      { id: "d8-3", text: "Cloud reference model" },
      { id: "d8-4", text: "Types of clouds" },
      { id: "d8-5", text: "Cloud infrastructure basics" },
    ],
  },
  {
    day: 9,
    title: "CC UNIT III & IV",
    subtitle: "Cloud Computing – Parallel Computing & Virtualization",
    subject: "Cloud Computing",
    topics: [
      { id: "d9-1", text: "Parallel vs distributed" },
      { id: "d9-2", text: "Elements of parallel computing" },
      { id: "d9-3", text: "Virtualization techniques" },
      { id: "d9-4", text: "VMware example" },
      { id: "d9-5", text: "Hardware virtualization (full, partial, para)" },
    ],
  },
  {
    day: 10,
    title: "ML UNIT I",
    subtitle: "Machine Learning – Foundations & Regression",
    subject: "Machine Learning",
    topics: [
      { id: "d10-1", text: "Types of ML" },
      { id: "d10-2", text: "Applications" },
      { id: "d10-3", text: "Binary vs multi-class vs multi-label" },
      { id: "d10-4", text: "Performance metrics" },
      { id: "d10-5", text: "Confusion matrix" },
      { id: "d10-6", text: "Accuracy, precision, recall" },
      { id: "d10-7", text: "ROC curve" },
      { id: "d10-8", text: "Linear regression" },
      { id: "d10-9", text: "Logistic regression" },
    ],
  },
  {
    day: 11,
    title: "ML UNIT II",
    subtitle: "Machine Learning – Classification & Ensemble Methods",
    subject: "Machine Learning",
    topics: [
      { id: "d11-1", text: "Decision Trees" },
      { id: "d11-2", text: "Tree splitting" },
      { id: "d11-3", text: "Pruning" },
      { id: "d11-4", text: "Rule-based classification" },
      { id: "d11-5", text: "Naive Bayes" },
      { id: "d11-6", text: "Bayesian Networks (definition only)" },
      { id: "d11-7", text: "KNN" },
      { id: "d11-8", text: "SVM" },
      { id: "d11-9", text: "Ensemble Learning" },
      { id: "d11-10", text: "Random Forest" },
    ],
  },
  {
    day: 12,
    title: "ML UNIT III & IV",
    subtitle: "Machine Learning – Neural Networks & Unsupervised Learning",
    subject: "Machine Learning",
    topics: [
      { id: "d12-h1", text: "Neural Networks", isHeader: true },
      { id: "d12-1", text: "Perceptron" },
      { id: "d12-2", text: "Adaline (light)" },
      { id: "d12-3", text: "MLP" },
      { id: "d12-4", text: "Activation functions" },
      { id: "d12-5", text: "Loss function" },
      { id: "d12-6", text: "Gradient descent" },
      { id: "d12-7", text: "Backprop" },
      { id: "d12-8", text: "Regularization" },
      { id: "d12-h2", text: "Unsupervised", isHeader: true },
      { id: "d12-9", text: "K-means" },
      { id: "d12-10", text: "Hierarchical clustering" },
      { id: "d12-11", text: "SOM (definition only)" },
      { id: "d12-12", text: "PCA" },
      { id: "d12-13", text: "Dimensionality reduction concept" },
      { id: "d12-14", text: "Variance explanation" },
      { id: "d12-h3", text: "PYQs", isHeader: true },
      { id: "d12-15", text: "1 long question from each ML unit" },
    ],
  },
]
